version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - aws ssm get-parameters --names "/${ENVIRONMENT_NAME}/${ENVIRONMENT_NUMBER}/buildkite-ssh-key" --with-decryption --output text --query 'Parameters[0].Value' > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
  build:
    commands:
      - echo Build started on `date`
      - /opt/buildkite/buildkite-agent bootstrap --build-path ${CODEBUILD_SRC_DIR} --bin-path /opt/buildkite
  post_build:
    commands:
      - echo Build completed on `date`
